version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: fintrack-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fintrack_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./FintrackPro-Backend
    container_name: fintrack-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fintrack_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

  frontend:
    build: ./FintrackPro-frontend
    container_name: fintrack-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql-data: